version: "3.7"
services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/starwarsapi
    container_name: apirest-starwars
    ports:
      - 8081:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo:latest
    container_name: apirest-mongodb
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge