version: "3.7"
services:
  springboot:
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/starwars
    container_name: starwars-rest-api
    ports:
      - 8081:8080
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - spring-mongo-net
  mongo:
    image: mongo:latest
    container_name: starwars-mongodb
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null
    networks:
      - spring-mongo-net
networks:
  spring-mongo-net:
    driver: bridge